- name: Generate users list
  hosts: localhost
  connection: local
  become: no
  gather_facts: no

  tasks:
    - name: generate users list
      set_fact:
        users: "{{ users|default([]) + [ {'name': 'student' + item, 'username': 'student' + item, 'email': 'student' + item + '@example.com'} ] }}"
      with_sequence: start="{{ student_count_start }}" end="{{ student_count_end }}"
      when: student_count_start is defined and student_count_end is defined

- name: Create lab instances in AWS
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  roles:
    - manage_ec2_instances

- name: Configure common options on managed nodes and control nodes
  hosts: "managed_nodes:control_nodes"
  become: yes
  roles:
    - user_accounts
    - common

- name: Configure control node
  hosts: control_nodes
  become: yes
  roles:
    - control_node

- name: Email inventory to instructor
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  roles:
    - email-instructor

